remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [LabVIEW Dependencies Inspector]
description: [open-source LabVIEW tool, designed to simplify the process of understanding LabVIEW files dependencies within your projects. By creating a clear, 2D visualization of your selected files relationships, 
you can quickly identify potential issues and optimize your code structure]
